### ISSUE TITLE
trim down to required modules

### ISSUE THREAD

**Issue by macfarla** [Consensys/tuweni#15]
besu uses

    api 'io.tmio:tuweni-bytes:2.4.2'
    api 'io.tmio:tuweni-config:2.4.2'
    api 'io.tmio:tuweni-concurrent:2.4.2'
    api 'io.tmio:tuweni-crypto:2.4.2'
    api 'io.tmio:tuweni-devp2p:2.4.2'
    api 'io.tmio:tuweni-io:2.4.2'
    api 'io.tmio:tuweni-net:2.4.2'
    api 'io.tmio:tuweni-rlp:2.4.2'
    api 'io.tmio:tuweni-toml:2.4.2'
    api 'io.tmio:tuweni-units:2.4.2'

teku uses a subset of these plus ssz

tuweni-bytes
tuweni-crypto
tuweni-io
tuweni-rlp
tuweni-ssz
tuweni-units

**Comment by lu-pinto** [comment]
Other possible uses:
- discovery-v5: https://github.com/consensys/discovery
- samba: https://github.com/meldsun0/samba/
- linea-tracer: https://github.com/Consensys/linea-tracer
- linea-besu: https://github.com/Consensys/linea-besu
- sumo
